// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SI2Proy.Models;

namespace SI2Proy.Migrations
{
    [DbContext(typeof(ProduccionContext))]
    partial class ProduccionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SI2Proy.Models.Agregado", b =>
                {
                    b.Property<int>("CodMateriaPrima")
                        .HasColumnName("cod_materia_prima");

                    b.Property<string>("NombreMateriaPrima")
                        .HasColumnName("nombre_materia_prima")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CodMateriaPrima")
                        .HasName("PK__Agregado__8262F779A7566A38");

                    b.ToTable("Agregado");
                });

            modelBuilder.Entity("SI2Proy.Models.Cliente", b =>
                {
                    b.Property<int>("NumeroCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_cliente")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<string>("Direccion")
                        .HasColumnName("direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("Convert(date,Getdate())");

                    b.Property<DateTime?>("FechaIngreso")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("fecha_ingreso")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("Convert(date,Getdate())");

                    b.Property<int?>("PrioridadCliente")
                        .HasColumnName("prioridad_cliente");

                    b.Property<string>("Telefono")
                        .HasColumnName("telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("TelefonoCelular")
                        .HasColumnName("telefono_celular")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("NumeroCliente")
                        .HasName("PK__Cliente__DA28746217A07AC9");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SI2Proy.Models.ControlCalidad", b =>
                {
                    b.Property<int>("NumeroControlCalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_control_calidad")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DetalleOrdenProduccionFk")
                        .HasColumnName("detalle_orden_produccion_fk");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Hora")
                        .HasColumnName("hora")
                        .HasColumnType("datetime");

                    b.Property<int?>("TamanoLote")
                        .HasColumnName("tamano_lote");

                    b.Property<int?>("TamanoMuestra")
                        .HasColumnName("tamano_muestra");

                    b.Property<int?>("TotalDefectos")
                        .HasColumnName("total_defectos");

                    b.HasKey("NumeroControlCalidad")
                        .HasName("PK__ControlC__CBF8F5AEFFE67087");

                    b.HasIndex("DetalleOrdenProduccionFk");

                    b.ToTable("ControlCalidad");
                });

            modelBuilder.Entity("SI2Proy.Models.DesgloseProyeccionLineaProduccion", b =>
                {
                    b.Property<int>("CodDesgloseLineaProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_desglose_linea_produccion")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DesgloseProyeccionProduccionMensualFk")
                        .HasColumnName("desglose_proyeccion_produccion_mensual_fk");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<int?>("LineaProduccionFk")
                        .HasColumnName("linea_produccion_fk");

                    b.Property<int?>("PorcentajeProduccion")
                        .HasColumnName("porcentaje_produccion");

                    b.Property<int?>("TotalCantProductoProducirMesLineaProduccion")
                        .HasColumnName("total_cant_producto_producir_mes_linea_produccion");

                    b.HasKey("CodDesgloseLineaProduccion")
                        .HasName("PK__Desglose__4623E72D7CBF22E7");

                    b.HasIndex("DesgloseProyeccionProduccionMensualFk");

                    b.HasIndex("LineaProduccionFk");

                    b.ToTable("DesgloseProyeccionLineaProduccion");
                });

            modelBuilder.Entity("SI2Proy.Models.DesgloseProyeccionProduccionMensual", b =>
                {
                    b.Property<int>("NumeroMesAno")
                        .HasColumnName("numero_mes_ano");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<int?>("NumeroProductosProyectadoFabricar")
                        .HasColumnName("numero_productos_proyectado_fabricar");

                    b.Property<string>("Observacion")
                        .HasColumnName("observacion")
                        .IsUnicode(false);

                    b.Property<int?>("PlanificacionProyeccionMensualFk")
                        .HasColumnName("planificacion_proyeccion_mensual_fk");

                    b.Property<int?>("TotalDiasLaboralesMes")
                        .HasColumnName("total_dias_laborales_mes");

                    b.Property<int?>("TotalProductoProducirMes")
                        .HasColumnName("total_producto_producir_mes");

                    b.HasKey("NumeroMesAno")
                        .HasName("PK__Desglose__4D6FBD777FDF122F");

                    b.HasIndex("PlanificacionProyeccionMensualFk");

                    b.ToTable("DesgloseProyeccionProduccionMensual");
                });

            modelBuilder.Entity("SI2Proy.Models.DetalleAprovisionamiento", b =>
                {
                    b.Property<int>("CodDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_detalle")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cantidad")
                        .HasColumnName("cantidad");

                    b.Property<bool?>("Ingresado")
                        .HasColumnName("ingresado");

                    b.Property<int?>("InventarioFk")
                        .HasColumnName("inventario_fk");

                    b.Property<string>("Observacion")
                        .HasColumnName("observacion")
                        .IsUnicode(false);

                    b.Property<int?>("OrdenAprovisionamientoFk")
                        .HasColumnName("orden_aprovisionamiento_fk");

                    b.HasKey("CodDetalle")
                        .HasName("PK__DetalleA__03E666AE79BED8D2");

                    b.HasIndex("InventarioFk");

                    b.HasIndex("OrdenAprovisionamientoFk");

                    b.ToTable("DetalleAprovisionamiento");
                });

            modelBuilder.Entity("SI2Proy.Models.DetalleControlCalidad", b =>
                {
                    b.Property<int>("CodDetalleControlCalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_detalle_control_calidad")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ControlCalidadFk")
                        .HasColumnName("control_calidad_fk");

                    b.Property<int?>("NoConformidadFk")
                        .HasColumnName("no_conformidad_fk");

                    b.Property<int?>("TotalNoConformidad")
                        .HasColumnName("total_no_conformidad");

                    b.HasKey("CodDetalleControlCalidad")
                        .HasName("PK__DetalleC__E6A8A05BAE951F38");

                    b.HasIndex("ControlCalidadFk");

                    b.HasIndex("NoConformidadFk");

                    b.ToTable("DetalleControlCalidad");
                });

            modelBuilder.Entity("SI2Proy.Models.DetalleOrdenProduccion", b =>
                {
                    b.Property<int>("CodDetalleOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_detalle_orden")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("ControlCalidad")
                        .HasColumnName("control_calidad");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnName("fecha_fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnName("fecha_inicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnName("hora_fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HoraInicio")
                        .HasColumnName("hora_inicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Observacion")
                        .HasColumnName("observacion")
                        .IsUnicode(false);

                    b.Property<int?>("OrdenProduccionFk")
                        .HasColumnName("orden_produccion_fk");

                    b.Property<int?>("ProcesoFk")
                        .HasColumnName("proceso_fk");

                    b.HasKey("CodDetalleOrden")
                        .HasName("PK__DetalleO__6EA4E1E7508AB731");

                    b.HasIndex("OrdenProduccionFk");

                    b.HasIndex("ProcesoFk");

                    b.ToTable("DetalleOrdenProduccion");
                });

            modelBuilder.Entity("SI2Proy.Models.DetallePedido", b =>
                {
                    b.Property<int>("CodDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_detalle")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CantidadDetalle")
                        .HasColumnName("cantidad_detalle");

                    b.Property<bool?>("DetallePedidoFinalizado")
                        .HasColumnName("detalle_pedido_finalizado");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModeloProductoFk")
                        .HasColumnName("modelo_producto_fk");

                    b.Property<int?>("PedidoFk")
                        .HasColumnName("pedido_fk");

                    b.Property<int?>("PrecioTotalDetalle")
                        .HasColumnName("precio_total_detalle");

                    b.HasKey("CodDetalle")
                        .HasName("PK__DetalleP__03E666AEB8CCCA85");

                    b.HasIndex("ModeloProductoFk");

                    b.HasIndex("PedidoFk");

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("SI2Proy.Models.Empresa", b =>
                {
                    b.Property<int>("NumeroCliente")
                        .HasColumnName("numero_cliente");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnName("nombre_empresa")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Representante")
                        .HasColumnName("representante")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Ruc")
                        .HasColumnName("ruc")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("NumeroCliente")
                        .HasName("PK__Empresa__DA2874623789EF19");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("SI2Proy.Models.EstructuraMaterialesBom", b =>
                {
                    b.Property<int>("CodBom")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_bom")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CantidadPorProducto")
                        .HasColumnName("cantidad_por_producto");
                        

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .IsUnicode(false);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaVigencia")
                        .HasColumnName("fecha_vigencia")
                        .HasColumnType("datetime");

                    b.Property<int?>("MateriaPrimaFk")
                        .HasColumnName("materia_prima_fk");

                    b.Property<int?>("ModeloProductoFk")
                        .HasColumnName("modelo_producto_fk");

                    b.Property<bool?>("Obligatorio")
                        .HasColumnName("obligatorio");

                    b.HasKey("CodBom")
                        .HasName("PK__Estructu__FD1B5E7BA3A1C2D8");

                    b.HasIndex("MateriaPrimaFk");

                    b.HasIndex("ModeloProductoFk");

                    b.ToTable("EstructuraMaterialesBom");
                });

            modelBuilder.Entity("SI2Proy.Models.Insumo", b =>
                {
                    b.Property<int>("CodInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_insumo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnName("fecha_creacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreInsumo")
                        .HasColumnName("nombre_insumo")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CodInsumo")
                        .HasName("PK__Insumo__72BC4A8886A0340E");

                    b.ToTable("Insumo");
                });

            modelBuilder.Entity("SI2Proy.Models.Inventario", b =>
                {
                    b.Property<int>("CodInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_inventario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgregadoFk")
                        .HasColumnName("agregado_fk");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaStockComprometido")
                        .HasColumnName("fecha_stock_comprometido")
                        .HasColumnType("datetime");

                    b.Property<int?>("PedirQ")
                        .HasColumnName("pedir_q");


                    b.Property<int?>("SaldoPro")
                        .HasColumnName("saldo_pro");


                    b.Property<int?>("StockComprometido")
                        .HasColumnName("stock_comprometido");


                    b.Property<int?>("StockMaximo")
                        .HasColumnName("stock_maximo");


                    b.Property<int?>("Total")
                        .HasColumnName("total");
                      

                    b.HasKey("CodInventario")
                        .HasName("PK__Inventar__C117239A45F2C627");

                    b.HasIndex("AgregadoFk");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("SI2Proy.Models.LineaProduccion", b =>
                {
                    b.Property<int>("NumeroLineaProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_linea_produccion")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .IsUnicode(false);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnName("fecha_creacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreLineaProduccion")
                        .HasColumnName("nombre_linea_produccion")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("NumeroLineaProduccion")
                        .HasName("PK__LineaPro__5126622EFD6E624F");

                    b.ToTable("LineaProduccion");
                });

            modelBuilder.Entity("SI2Proy.Models.MateriaPrima", b =>
                {
                    b.Property<int>("CodMateriaPrima")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_materia_prima")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Activo")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .IsUnicode(false);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnName("fecha_creacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<int?>("InsumoFk")
                        .HasColumnName("insumo_fk");

                    b.Property<string>("Tipo")
                        .HasColumnName("tipo")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int?>("UnidadMedidaFk")
                        .HasColumnName("unidad_medida_fk");

                    b.HasKey("CodMateriaPrima")
                        .HasName("PK__MateriaP__8262F779239DF52C");

                    b.HasIndex("InsumoFk");

                    b.HasIndex("UnidadMedidaFk");

                    b.ToTable("MateriaPrima");
                });

            modelBuilder.Entity("SI2Proy.Models.ModeloProducto", b =>
                {
                    b.Property<int>("CodEstructuraMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_estructura_materia")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoProducto")
                        .HasColumnName("codigo_producto")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<bool?>("Estado")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<int?>("LineaProduccionFk")
                        .HasColumnName("linea_produccion_fk");

                    b.Property<string>("NombreModelo")
                        .HasColumnName("nombre_modelo")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Observaciones")
                        .HasColumnName("observaciones")
                        .IsUnicode(false);

                    b.Property<int?>("PrecioUnitario")
                        .HasColumnName("precio_unitario");
                       

                    b.Property<string>("TamanoEstandar")
                        .HasColumnName("tamano_estandar")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.HasKey("CodEstructuraMateria")
                        .HasName("PK__ModeloPr__A480511FE32FE033");

                    b.HasIndex("LineaProduccionFk");

                    b.ToTable("ModeloProducto");
                });

            modelBuilder.Entity("SI2Proy.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("CodMovimientoInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_movimiento_inventario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cantidad")
                        .HasColumnName("cantidad");
                       

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<string>("Factura")
                        .HasColumnName("factura")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaMovimiento")
                        .HasColumnName("fecha_movimiento")
                        .HasColumnType("datetime");

                    b.Property<int?>("InventarioFk")
                        .HasColumnName("inventario_fk");

                    b.Property<string>("Observacion")
                        .HasColumnName("observacion")
                        .IsUnicode(false);

                    b.Property<int?>("OrdenAprovisionamientoFk")
                        .HasColumnName("orden_aprovisionamiento_fk");

                    b.Property<int?>("PrecioUnitario")
                        .HasColumnName("precio_unitario");
                       

                    b.Property<int?>("ProveedorFk")
                        .HasColumnName("proveedor_fk");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnName("tipo_movimiento")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("CodMovimientoInventario")
                        .HasName("PK__Movimien__89910E5B993312B1");

                    b.HasIndex("InventarioFk");

                    b.HasIndex("OrdenAprovisionamientoFk");

                    b.HasIndex("ProveedorFk");

                    b.ToTable("MovimientoInventario");
                });

            modelBuilder.Entity("SI2Proy.Models.NoConformidad", b =>
                {
                    b.Property<int>("CodNoConformidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_no_conformidad")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionNoConformidad")
                        .HasColumnName("descripcion_no_conformidad")
                        .IsUnicode(false);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProcesoFk")
                        .HasColumnName("proceso_fk");

                    b.HasKey("CodNoConformidad")
                        .HasName("PK__NoConfor__823817DF60383558");

                    b.HasIndex("ProcesoFk");

                    b.ToTable("NoConformidad");
                });

            modelBuilder.Entity("SI2Proy.Models.OrdenAprovisionamiento", b =>
                {
                    b.Property<int>("NumeroOrdenAprovisionamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_orden_aprovisionamiento")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Aprobado")
                        .HasColumnName("aprobado");

                    b.Property<string>("AprobadoPor")
                        .HasColumnName("aprobado_por");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<bool?>("EstadoEntregado")
                        .HasColumnName("estado_entregado");

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnName("fecha_emision")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnName("fecha_entrega")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEstimadaEntrega")
                        .HasColumnName("fecha_estimada_entrega")
                        .HasColumnType("datetime");

                    b.Property<string>("Observacion")
                        .HasColumnName("observacion")
                        .IsUnicode(false);

                    b.HasKey("NumeroOrdenAprovisionamiento")
                        .HasName("PK__OrdenApr__947A2E27C09663E0");

                    b.ToTable("OrdenAprovisionamiento");
                });

            modelBuilder.Entity("SI2Proy.Models.OrdenProduccion", b =>
                {
                    b.Property<int>("NumeroTarjetaFabricacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_tarjeta_fabricacion")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Cerco")
                        .HasColumnName("cerco");

                    b.Property<string>("Corrida")
                        .HasColumnName("corrida")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnName("fecha_creacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan?>("HoraCreacion")
                        .HasColumnName("hora_creacion");

                    b.Property<int?>("PlanMaestroProduccionDetalladoFk")
                        .HasColumnName("plan_maestro_produccion_detallado_fk");

                    b.HasKey("NumeroTarjetaFabricacion")
                        .HasName("PK__OrdenPro__6F9C2C8232BD01C0");

                    b.HasIndex("PlanMaestroProduccionDetalladoFk");

                    b.ToTable("OrdenProduccion");
                });

            modelBuilder.Entity("SI2Proy.Models.Pedido", b =>
                {
                    b.Property<int>("NumeroOrdenCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_orden_compra")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cantidad")
                        .HasColumnName("cantidad");

                    b.Property<int?>("ClienteFk")
                        .HasColumnName("cliente_fk");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnName("fecha_entrega")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRealEntregaPedido")
                        .HasColumnName("fecha_real_entrega_pedido")
                        .HasColumnType("datetime");

                    b.Property<string>("NumeroNotaPedido")
                        .HasColumnName("numero_nota_pedido")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Observaciones")
                        .HasColumnName("observaciones")
                        .IsUnicode(false);

                    b.Property<bool?>("PedidoFinalizado")
                        .HasColumnName("pedido_finalizado");

                    b.Property<int?>("PrecioTotal")
                        .HasColumnName("precio_total");
                      

                    b.Property<int?>("VendedorFk")
                        .HasColumnName("vendedor_fk");

                    b.HasKey("NumeroOrdenCompra")
                        .HasName("PK__Pedido__6481E6FF5183D7AA");

                    b.HasIndex("ClienteFk");

                    b.HasIndex("VendedorFk");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("SI2Proy.Models.Persona", b =>
                {
                    b.Property<int>("NumeroCliente")
                        .HasColumnName("numero_cliente");

                    b.Property<string>("NombreCliente")
                        .HasColumnName("nombre_cliente")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NumeroCedula")
                        .HasColumnName("numero_cedula")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("NumeroCliente")
                        .HasName("PK__Persona__DA287462BB0C368A");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("SI2Proy.Models.PlanMaestroProduccion", b =>
                {
                    b.Property<int>("NumeroIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_ingreso")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DetallePedidoFk")
                        .HasColumnName("detalle_pedido_fk");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnName("fecha_ingreso")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaPrevistaIngresoProd")
                        .HasColumnName("fecha_prevista_ingreso_prod")
                        .HasColumnType("datetime");

                    b.Property<int?>("LineaProduccionFk")
                        .HasColumnName("linea_produccion_fk");

                    b.Property<DateTime?>("MesAnio")
                        .HasColumnName("mes_anio")
                        .HasColumnType("datetime");

                    b.Property<int?>("NumeroLote")
                        .HasColumnName("numero_lote");

                    b.Property<string>("Observaciones")
                        .HasColumnName("observaciones")
                        .IsUnicode(false);

                    b.HasKey("NumeroIngreso")
                        .HasName("PK__PlanMaes__E4D17A3472A832F0");

                    b.HasIndex("DetallePedidoFk");

                    b.HasIndex("LineaProduccionFk");

                    b.ToTable("PlanMaestroProduccion");
                });

            modelBuilder.Entity("SI2Proy.Models.PlanMaestroProduccionDetallado", b =>
                {
                    b.Property<int>("NumeroIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_ingreso")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Dia")
                        .HasColumnName("dia")
                        .HasColumnType("datetime");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaIngresoHojaRuta")
                        .HasColumnName("fecha_ingreso_hoja_ruta")
                        .HasColumnType("datetime");

                    b.Property<string>("Observaciones")
                        .HasColumnName("observaciones")
                        .IsUnicode(false);

                    b.Property<int?>("PlanMaestroProduccionFk")
                        .HasColumnName("plan_maestro_produccion_fk");

                    b.HasKey("NumeroIngreso")
                        .HasName("PK__PlanMaes__E4D17A34F0D6B101");

                    b.HasIndex("PlanMaestroProduccionFk");

                    b.ToTable("PlanMaestroProduccionDetallado");
                });

            modelBuilder.Entity("SI2Proy.Models.PlanificacionProyeccionMensual", b =>
                {
                    b.Property<int>("Anio")
                        .HasColumnName("anio");

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.HasKey("Anio")
                        .HasName("PK__Planific__61B22F47AF885FBE");

                    b.ToTable("PlanificacionProyeccionMensual");
                });

            modelBuilder.Entity("SI2Proy.Models.Proceso", b =>
                {
                    b.Property<int>("CodProceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_proceso")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionProceso")
                        .HasColumnName("descripcion_proceso")
                        .IsUnicode(false);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<int?>("LineaProduccionFk")
                        .HasColumnName("linea_produccion_fk");

                    b.Property<string>("NombreProceso")
                        .HasColumnName("nombre_proceso")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CodProceso")
                        .HasName("PK__Proceso__2766286A30BEB0EE");

                    b.HasIndex("LineaProduccionFk");

                    b.ToTable("Proceso");
                });

            modelBuilder.Entity("SI2Proy.Models.Proveedor", b =>
                {
                    b.Property<int>("NumeroProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_proveedor")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<string>("Direccion")
                        .HasColumnName("direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreProveedor")
                        .HasColumnName("nombre_proveedor")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NumeroCedulaRuc")
                        .HasColumnName("numero_cedula_ruc")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Telefono")
                        .HasColumnName("telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("TelefonoCelular")
                        .HasColumnName("telefono_celular")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("NumeroProveedor")
                        .HasName("PK__Proveedo__46389B1FF80FBB44");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("SI2Proy.Models.TiempoProduccion", b =>
                {
                    b.Property<int>("NumeroIngresoT")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_ingreso_t")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaJornada")
                        .HasColumnName("fecha_jornada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HoraFinJornada")
                        .HasColumnName("hora_fin_jornada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HoraInicioJornada")
                        .HasColumnName("hora_inicio_jornada")
                        .HasColumnType("datetime");

                    b.Property<int?>("NumeroObreros")
                        .HasColumnName("numero_obreros");

                    b.Property<string>("Observacion")
                        .HasColumnName("observacion")
                        .IsUnicode(false);

                    b.Property<int?>("ProcesoFk")
                        .HasColumnName("proceso_fk");

                    b.Property<DateTime?>("TiempoLaborado")
                        .HasColumnName("tiempo_laborado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TiempoTotalReceso")
                        .HasColumnName("tiempo_total_receso")
                        .HasColumnType("datetime");

                    b.HasKey("NumeroIngresoT")
                        .HasName("PK__TiempoPr__76D9FA3A4B7D4349");

                    b.HasIndex("ProcesoFk");

                    b.ToTable("TiempoProduccion");
                });

            modelBuilder.Entity("SI2Proy.Models.UnidadMedida", b =>
                {
                    b.Property<int>("CodUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_unidad_medida")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura")
                        .HasColumnName("abreviatura")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreUnidadMedida")
                        .HasColumnName("nombre_unidad_medida")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CodUnidadMedida")
                        .HasName("PK__UnidadMe__707C839684C4E587");

                    b.ToTable("UnidadMedida");
                });

            modelBuilder.Entity("SI2Proy.Models.Vendedor", b =>
                {
                    b.Property<int>("NumeroVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero_vendedor")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Digitador")
                        .HasColumnName("digitador")
                        .IsUnicode(false);

                    b.Property<string>("Direccion")
                        .HasColumnName("direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaDigitador")
                        .HasColumnName("fecha_digitador")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreVendedor")
                        .HasColumnName("nombre_vendedor")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NumeroCedula")
                        .HasColumnName("numero_cedula")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("NumeroRuc")
                        .HasColumnName("numero_ruc")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int?>("RecordVentas")
                        .HasColumnName("record_ventas");

                    b.Property<string>("Telefono")
                        .HasColumnName("telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("TelefonoCelular")
                        .HasColumnName("telefono_celular")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("NumeroVendedor")
                        .HasName("PK__Vendedor__C64BE7BAF9B04D45");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("SI2Proy.Models.Agregado", b =>
                {
                    b.HasOne("SI2Proy.Models.MateriaPrima", "CodMateriaPrimaNavigation")
                        .WithOne("Agregado")
                        .HasForeignKey("SI2Proy.Models.Agregado", "CodMateriaPrima")
                        .HasConstraintName("FK__Agregado__cod_ma__0C85DE4D")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.ControlCalidad", b =>
                {
                    b.HasOne("SI2Proy.Models.DetalleOrdenProduccion", "DetalleOrdenProduccionFkNavigation")
                        .WithMany("ControlCalidadNavigation")
                        .HasForeignKey("DetalleOrdenProduccionFk")
                        .HasConstraintName("FK__ControlCa__detal__787EE5A0")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.DesgloseProyeccionLineaProduccion", b =>
                {
                    b.HasOne("SI2Proy.Models.DesgloseProyeccionProduccionMensual", "DesgloseProyeccionProduccionMensualFkNavigation")
                        .WithMany("DesgloseProyeccionLineaProduccion")
                        .HasForeignKey("DesgloseProyeccionProduccionMensualFk")
                        .HasConstraintName("FK__DesgloseP__desgl__6477ECF3")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SI2Proy.Models.LineaProduccion", "LineaProduccionFkNavigation")
                        .WithMany("DesgloseProyeccionLineaProduccion")
                        .HasForeignKey("LineaProduccionFk")
                        .HasConstraintName("FK__DesgloseP__linea__656C112C")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.DesgloseProyeccionProduccionMensual", b =>
                {
                    b.HasOne("SI2Proy.Models.PlanificacionProyeccionMensual", "PlanificacionProyeccionMensualFkNavigation")
                        .WithMany("DesgloseProyeccionProduccionMensual")
                        .HasForeignKey("PlanificacionProyeccionMensualFk")
                        .HasConstraintName("FK__DesgloseP__plani__619B8048")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.DetalleAprovisionamiento", b =>
                {
                    b.HasOne("SI2Proy.Models.Inventario", "InventarioFkNavigation")
                        .WithMany("DetalleAprovisionamiento")
                        .HasForeignKey("InventarioFk")
                        .HasConstraintName("FK__DetalleAp__inven__1AD3FDA4")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SI2Proy.Models.OrdenAprovisionamiento", "OrdenAprovisionamientoFkNavigation")
                        .WithMany("DetalleAprovisionamiento")
                        .HasForeignKey("OrdenAprovisionamientoFk")
                        .HasConstraintName("FK__DetalleAp__orden__19DFD96B")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.DetalleControlCalidad", b =>
                {
                    b.HasOne("SI2Proy.Models.ControlCalidad", "ControlCalidadFkNavigation")
                        .WithMany("DetalleControlCalidad")
                        .HasForeignKey("ControlCalidadFk")
                        .HasConstraintName("FK__DetalleCo__contr__7E37BEF6")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SI2Proy.Models.NoConformidad", "NoConformidadFkNavigation")
                        .WithMany("DetalleControlCalidad")
                        .HasForeignKey("NoConformidadFk")
                        .HasConstraintName("FK__DetalleCo__no_co__7F2BE32F")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.DetalleOrdenProduccion", b =>
                {
                    b.HasOne("SI2Proy.Models.OrdenProduccion", "OrdenProduccionFkNavigation")
                        .WithMany("DetalleOrdenProduccion")
                        .HasForeignKey("OrdenProduccionFk")
                        .HasConstraintName("FK__DetalleOr__orden__74AE54BC");

                    b.HasOne("SI2Proy.Models.Proceso", "ProcesoFkNavigation")
                        .WithMany("DetalleOrdenProduccion")
                        .HasForeignKey("ProcesoFk")
                        .HasConstraintName("FK__DetalleOr__proce__75A278F5");
                });

            modelBuilder.Entity("SI2Proy.Models.DetallePedido", b =>
                {
                    b.HasOne("SI2Proy.Models.ModeloProducto", "ModeloProductoFkNavigation")
                        .WithMany("DetallePedido")
                        .HasForeignKey("ModeloProductoFk")
                        .HasConstraintName("FK__DetallePe__model__5CD6CB2B")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SI2Proy.Models.Pedido", "PedidoFkNavigation")
                        .WithMany("DetallePedido")
                        .HasForeignKey("PedidoFk")
                        .HasConstraintName("FK__DetallePe__pedid__5BE2A6F2")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.Empresa", b =>
                {
                    b.HasOne("SI2Proy.Models.Cliente", "NumeroClienteNavigation")
                        .WithOne("Empresa")
                        .HasForeignKey("SI2Proy.Models.Empresa", "NumeroCliente")
                        .HasConstraintName("FK__Empresa__numero___4E88ABD4")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.EstructuraMaterialesBom", b =>
                {
                    b.HasOne("SI2Proy.Models.MateriaPrima", "MateriaPrimaFkNavigation")
                        .WithMany("EstructuraMaterialesBom")
                        .HasForeignKey("MateriaPrimaFk")
                        .HasConstraintName("FK__Estructur__mater__0F624AF8")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SI2Proy.Models.ModeloProducto", "ModeloProductoFkNavigation")
                        .WithMany("EstructuraMaterialesBom")
                        .HasForeignKey("ModeloProductoFk")
                        .HasConstraintName("FK__Estructur__model__10566F31")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.Inventario", b =>
                {
                    b.HasOne("SI2Proy.Models.Agregado", "AgregadoFkNavigation")
                        .WithMany("Inventario")
                        .HasForeignKey("AgregadoFk")
                        .HasConstraintName("FK__Inventari__agreg__1332DBDC")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.MateriaPrima", b =>
                {
                    b.HasOne("SI2Proy.Models.Insumo", "InsumoFkNavigation")
                        .WithMany("MateriaPrima")
                        .HasForeignKey("InsumoFk")
                        .HasConstraintName("FK__MateriaPr__insum__08B54D69")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SI2Proy.Models.UnidadMedida", "UnidadMedidaFkNavigation")
                        .WithMany("MateriaPrima")
                        .HasForeignKey("UnidadMedidaFk")
                        .HasConstraintName("FK__MateriaPr__unida__09A971A2")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.ModeloProducto", b =>
                {
                    b.HasOne("SI2Proy.Models.LineaProduccion", "LineaProduccionFkNavigation")
                        .WithMany("ModeloProducto")
                        .HasForeignKey("LineaProduccionFk")
                        .HasConstraintName("FK__ModeloPro__linea__59063A47")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.MovimientoInventario", b =>
                {
                    b.HasOne("SI2Proy.Models.Inventario", "InventarioFkNavigation")
                        .WithMany("MovimientoInventario")
                        .HasForeignKey("InventarioFk")
                        .HasConstraintName("FK__Movimient__inven__1DB06A4F");

                    b.HasOne("SI2Proy.Models.OrdenAprovisionamiento", "OrdenAprovisionamientoFkNavigation")
                        .WithMany("MovimientoInventario")
                        .HasForeignKey("OrdenAprovisionamientoFk")
                        .HasConstraintName("FK__Movimient__orden__1F98B2C1");

                    b.HasOne("SI2Proy.Models.Proveedor", "ProveedorFkNavigation")
                        .WithMany("MovimientoInventario")
                        .HasForeignKey("ProveedorFk")
                        .HasConstraintName("FK__Movimient__prove__1EA48E88");
                });

            modelBuilder.Entity("SI2Proy.Models.NoConformidad", b =>
                {
                    b.HasOne("SI2Proy.Models.Proceso", "ProcesoFkNavigation")
                        .WithMany("NoConformidad")
                        .HasForeignKey("ProcesoFk")
                        .HasConstraintName("FK__NoConform__proce__7B5B524B")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.OrdenProduccion", b =>
                {
                    b.HasOne("SI2Proy.Models.PlanMaestroProduccionDetallado", "PlanMaestroProduccionDetalladoFkNavigation")
                        .WithMany("OrdenProduccion")
                        .HasForeignKey("PlanMaestroProduccionDetalladoFk")
                        .HasConstraintName("FK__OrdenProd__plan___6EF57B66")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.Pedido", b =>
                {
                    b.HasOne("SI2Proy.Models.Cliente", "ClienteFkNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("ClienteFk")
                        .HasConstraintName("FK__Pedido__cliente___534D60F1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SI2Proy.Models.Vendedor", "VendedorFkNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("VendedorFk")
                        .HasConstraintName("FK__Pedido__vendedor__5441852A")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.Persona", b =>
                {
                    b.HasOne("SI2Proy.Models.Cliente", "NumeroClienteNavigation")
                        .WithOne("Persona")
                        .HasForeignKey("SI2Proy.Models.Persona", "NumeroCliente")
                        .HasConstraintName("FK__Persona__numero___4BAC3F29")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.PlanMaestroProduccion", b =>
                {
                    b.HasOne("SI2Proy.Models.DetallePedido", "DetallePedidoFkNavigation")
                        .WithMany("PlanMaestroProduccion")
                        .HasForeignKey("DetallePedidoFk")
                        .HasConstraintName("FK__PlanMaest__detal__693CA210");

                    b.HasOne("SI2Proy.Models.LineaProduccion", "LineaProduccionFkNavigation")
                        .WithMany("PlanMaestroProduccion")
                        .HasForeignKey("LineaProduccionFk")
                        .HasConstraintName("FK__PlanMaest__linea__68487DD7")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.PlanMaestroProduccionDetallado", b =>
                {
                    b.HasOne("SI2Proy.Models.PlanMaestroProduccion", "PlanMaestroProduccionFkNavigation")
                        .WithMany("PlanMaestroProduccionDetallado")
                        .HasForeignKey("PlanMaestroProduccionFk")
                        .HasConstraintName("FK__PlanMaest__plan___6C190EBB")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.Proceso", b =>
                {
                    b.HasOne("SI2Proy.Models.LineaProduccion", "LineaProduccionFkNavigation")
                        .WithMany("Proceso")
                        .HasForeignKey("LineaProduccionFk")
                        .HasConstraintName("FK__Proceso__linea_p__71D1E811")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SI2Proy.Models.TiempoProduccion", b =>
                {
                    b.HasOne("SI2Proy.Models.Proceso", "ProcesoFkNavigation")
                        .WithMany("TiempoProduccion")
                        .HasForeignKey("ProcesoFk")
                        .HasConstraintName("FK__TiempoPro__proce__02084FDA")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
